### ISSUE TITLE
Did run "npm install" with only node installed

### ISSUE THREAD

**Issue by fabianhenzler** [epayet/mjml-starter-kit#4]
Hi,
just found your repo and am super happy, because it seems to spare me a lot of work :)

Sadly I can't get it working :(
I have only node installed globally and did run `npm install`
After everything runs thorugh I run `npm start` but I get
```
➜  marketo-email-template git:(master) ✗ npm start

> marketo-email-template@1.0.0 start /Users/fabianhenzler/Sites/marketo-email-template
> gulp

/Users/fabianhenzler/Sites/marketo-email-template/components/index.js:5
export default CustomElements;
^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at loader (/Users/fabianhenzler/Sites/marketo-email-template/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/fabianhenzler/Sites/marketo-email-template/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/fabianhenzler/Sites/marketo-email-template/gulpfile.js:4:1)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! marketo-email-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the marketo-email-template@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the marketo-email-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs marketo-email-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls marketo-email-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fabianhenzler/Sites/marketo-email-template/npm-debug.log
```

npm-debug.log
```
23 error If you do, this is most likely a problem with the marketo-email-template package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs marketo-email-template
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls marketo-email-template
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Can you help? :)
Do I need to install something globally like browsersync?
Sorry have been out of dev for a year now and back to noob status ;)

Thanks in advance for your support :)

**Comment by epayet** [comment]
Hi sure no problem.
You did what you were supposed to do: `npm install` then `npm start`.
You don't need any other dependency.

The error you have means that ES6 (recent version of JS) is not supported. 
That's weird though, because in the repo we use `require('babel-register');` that should take care of that.

Can you run `npm run build` and see if you have the same issue?

Also, are you sure that the command `npm install` went 100% ok? If you're unsure, you could remove the `node_modules` folder and do `npm install` again.

Happy to help :)

**Comment by fabianhenzler** [comment]
seems to be my fault - removed node_modules and installed again - now it work :)

Thanks! You're awesome 🥇

**Comment by epayet** [comment]
Cool! I'm happy to hear that, don't hesitate if you need anything else or if you have some feedback on the starter-kit.

Best regards.
